#!/usr/bin/env bash
# Script that configure HAproxy on lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 71430-web-01 54.173.182.190 check port 80
        server 71430-web-02 54.162.77.61 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
