#!/usr/bin/env bash
# Script that configure HAproxy on lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 77097-web-01 54.146.68.43 check port 80
        server 77097-web-02 18.233.65.183 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
